name: Get Context

on: 
  workflow_dispatch

jobs:
  Context-Details:
    runs-on: ubuntu-latest
    steps:
      - env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
