name: Read Secrets
run-name: ${{ github.actor }} reading secrets 🚀
on: workflow_dispatch
jobs:
  Reading-Secrets:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Job is triggerred by ${{ github.event_name }}"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Reading Secrets
        run: echo "Env secret is ${{ secrets.TEST_SECRET}}"
      
    
    
