name: Read Secrets
run-name: ${{ github.actor }} reading secrets 🚀

on: 
  workflow_dispatch:

jobs:
  Reading-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show Trigger Info
        run: echo "Job is triggered by ${{ github.event_name }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Reading Secrets
        env:
          SUPER_SECRET: ${{ secrets.TEST_SECRET }}
          ENV_SEC: ${{ secrets.ENV_VAR }}
        run: |
          echo "Super Secret: $SUPER_SECRET"
          echo "Env Sec: $ENV_SEC"
